version: 2
jobs:
  server:
    working_directory: ~/delivery/
    docker:
      # Must be node 14 because our docker container for user  is node 14
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          command: npm install && export NODE_ENV=test && npm run test
  client:
    working_directory: ~/delivery/
    docker:
      # Must be node 13 because our docker container for client  is node 13
      - image: circleci/node:13
    steps:
      - checkout
      - run: cd client && npm install
      - run: cd client && CI=true npm run build
      - run: cd client && npm test
      - run: cd client && npm run coverage
workflows:
  version: 2
  Test-Servers-and-Client:
    jobs:
      # - client
